Repository ZeroBGG/zero-gg, pull requests merged in 2023-01, with the labels that each got.

#4 ✨ Feat: #3 - Header 컴포넌트 추가
  src/components/Common/Header/Header.module.scss
  src/components/Common/Header/Header.tsx
  src/index.css
  src/index.tsx
Labels: Feat

#6 :sparkles: Feat: #6 - firebase 추가
  package-lock.json
  package.json
  src/components/Duo/Duo.tsx
  src/firebase.ts
  src/index.tsx
Labels: Feat

#9 ✨ Feat: #8 - Footer 컴포넌트 추가
  package-lock.json
  package.json
  src/assets/icons/logo.png
  src/components/Common/Footer/Footer.module.scss
  src/components/Common/Footer/Footer.tsx
  src/index.css
  src/index.tsx
Labels: Feat

#11 🎨 Refactor: #10 - 폴더 구조 리팩토링
  .prettierrc.json
  prettierrc.js
  src/index.tsx
  src/route.tsx
Labels: Refactor

#13 📝 Docs: #12 pull_request_template 추가
  .eslintignore
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Docs

#15 ✨ Feat: #14 Firebase DB 추가
  src/components/Common/Header/Header.module.scss
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoArr.ts
  src/components/Duo/DuoType.ts
Labels: Feat

#16 :sparkles: Feat: #17 LCK TeamSquad 완성
  package-lock.json
  package.json
  src/assets/icons/lane/Bottom.svg
  src/assets/icons/lane/Jungle.svg
  src/assets/icons/lane/Middle.svg
  src/assets/icons/lane/Support.svg
  src/assets/icons/lane/Top.svg
  src/assets/images/Logo/lck_log.png
  src/assets/images/Logo/lck_log_dark.png
  src/assets/images/Team/none.png
  src/components/LCK/LCK.module.scss
  src/components/LCK/LCK.tsx
  src/components/LCK/components/LanePostion/LanePositon.tsx
  src/components/LCK/components/Player/Player.module.scss
  src/components/LCK/components/Player/Player.tsx
  src/components/LCK/components/PlayerList/PlayerList.module.scss
  src/components/LCK/components/PlayerList/PlayerList.tsx
  src/components/LCK/components/TeamSlide/TeamSlide.module.scss
  src/components/LCK/components/TeamSlide/TeamSlide.tsx
  src/components/LCK/typings/index.ts
  src/data/teamSquad.json
Labels: Feat

#22 :ambulance: : Refactor: GlobalStyle 폴더 및 Scss추가
  src/components/Duo/Duo.module.scss
  src/components/LCK/components/Team/Player/Player.module.scss
  src/components/LCK/components/Team/Player/Player.tsx
  src/components/LCK/components/Team/PlayerList/List.tsx
  src/components/LCK/components/Team/PlayerList/PlayerList.module.scss
  src/components/LCK/components/Team/PlayerList/PlayerList.tsx
  src/components/LCK/components/Team/PlayerList/motion/index.ts
  src/components/LCK/components/Team/TeamSlide/TeamSlide.module.scss
  src/components/LCK/components/Team/TeamSlide/TeamSlide.tsx
  src/components/LCK/components/Team/TeamSlide/responsive.module.scss
  src/components/LCK/typings/index.ts
  src/styles/global.scss
Labels: Refactor

#24 🎨Refactor: #23 - 공통 및 스타일 구조 리팩토링
  src/api/championApi.ts
  src/components/Common/Footer/Footer.module.scss
  src/components/Main/Circle.module.scss
  src/components/Main/Circle.tsx
  src/components/Main/Main.module.scss
  src/components/Main/Main.tsx
  src/constants/url.ts
  src/index.tsx
  src/styles/_reset.scss
  src/styles/global.scss
Labels: Refactor

#25 Feat/lck 2
  src/components/LCK/LCK.module.scss
  src/components/LCK/LCK.tsx
  src/components/LCK/common.scss
  src/components/LCK/components/Team/Player/Player.module.scss
  src/components/LCK/components/Team/Player/Player.tsx
  src/components/LCK/components/Team/PlayerList/List.tsx
  src/components/LCK/components/Team/PlayerList/PlayerList.module.scss
  src/components/LCK/components/Team/PlayerList/motion/index.ts
  src/components/LCK/components/Team/PlayerList/varients/index.ts
  src/components/LCK/components/Team/Team.module.scss
  src/components/LCK/components/Team/TeamSlide/TeamSlide.module.scss
  src/components/LCK/components/Team/TeamSlide/responsive.module.scss
  src/components/LCK/components/Team/responsive.module.scss
  src/styles/_reset.scss
Labels: Feat

#26 🎨Refactor : Multiple-Filter 작업 진행 중
  package-lock.json
  package.json
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoArr.ts
  src/components/Duo/DuoCards/DuoCards.module.scss
  src/components/Duo/DuoCards/DuoCards.tsx
  src/components/Duo/DuoInfo/DuoInfo.module.scss
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/Duo/DuoType.ts
  src/components/Duo/WriteDuo/WriteDuo.module.scss
  src/components/Duo/WriteDuo/WriteDuo.tsx
  src/components/Duo/utils/DuoArr.ts
  src/components/Duo/utils/DuoType.ts
  src/hooks/useInput.tsx
  src/route.tsx
Labels: Feat

#28 ✨ Feat: #17 - Main 컴포넌트 추가
  src/components/Common/Footer/Footer.module.scss
  src/components/Common/Header/Header.module.scss
  src/components/Common/Header/Header.tsx
  src/components/Main/Circle.tsx
  src/components/Main/InputID.module.scss
  src/components/Main/InputID.tsx
  src/components/Main/Main.module.scss
  src/components/Main/Main.tsx
  src/route.tsx
  src/styles/global.scss
Labels: Feat

#35 ✨ Feat: #29 - 소환사 정보 조회 기능 추가
  src/api/championApi.ts
  src/api/summonerApi.ts
  src/assets/images/Record/emblems/bronze.png
  src/assets/images/Record/emblems/challenger.png
  src/assets/images/Record/emblems/diamond.png
  src/assets/images/Record/emblems/gold.png
  src/assets/images/Record/emblems/grandmaster.png
  src/assets/images/Record/emblems/master.png
  src/assets/images/Record/emblems/platinum.png
  src/assets/images/Record/emblems/silver.png
  src/assets/images/Record/emblems/unranked.png
  src/components/Record/Record.module.scss
  src/components/Record/Record.tsx
  src/components/Record/SummonerInfo/SummonerInfo.module.scss
  src/components/Record/SummonerInfo/SummonerInfo.tsx
  src/components/Record/SummonerRank/SummonerRank.module.scss
  src/components/Record/SummonerRank/SummonerRank.tsx
  src/components/Record/types/type.ts
  src/constants/.gitkeep
  src/constants/url.ts
Labels: Feat

#36 🎨Design: #18 - Duo Components CSS 작업 완료
  src/assets/images/Tier/Bronze.png
  src/assets/images/Tier/Challenger.png
  src/assets/images/Tier/Diamond.png
  src/assets/images/Tier/Gold.png
  src/assets/images/Tier/GrandMaster.png
  src/assets/images/Tier/Iron.png
  src/assets/images/Tier/Master.png
  src/assets/images/Tier/Platinum.png
  src/assets/images/Tier/Silver.png
  src/components/Duo/Constants/constant.ts
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.module.scss
  src/components/Duo/DuoCards/DuoCards.tsx
  src/components/Duo/DuoInfo/DuoInfo.module.scss
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/Duo/WriteDuo/WriteDuo.module.scss
  src/components/Duo/WriteDuo/WriteDuo.tsx
  src/components/Duo/common.scss
  src/components/Duo/utils/DuoArr.ts
  src/components/Duo/utils/DuoType.ts
  src/route.tsx
  src/styles/_reset.scss
  src/styles/global.scss
Labels: Refactor

#38 Docs: pull_request_template 수정
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: Docs

#44 ✨ Feat #33 - Duo 찾기 Filter 기능 추가
  package-lock.json
  package.json
  src/components/Duo/Common/InputText.module.scss
  src/components/Duo/Common/InputText.tsx
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.module.scss
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/Duo/WriteDuo/WriteDuo.tsx
  src/components/Duo/common.scss
Labels: Feat, Fix, Refactor

#45 ✨ Feat: #37 - 소환사 전적 검색 기능 추가
  package.json
  src/api/matchAPi.ts
  src/api/staticDataApi.ts
  src/components/Duo/Duo.module.scss
  src/components/Main/InputID.tsx
  src/components/Record/Record.tsx
  src/components/Record/SummonerMatch/MatchInfo.module.scss
  src/components/Record/SummonerMatch/MatchInfo.tsx
  src/components/Record/SummonerMatch/SummonerMatch.module.scss
  src/components/Record/SummonerMatch/SummonerMatch.tsx
  src/components/Record/SummonerRank/SummonerRank.tsx
  src/components/Record/types/type.ts
  src/constants/data.ts
  src/constants/url.ts
  src/route.tsx
Labels: Feat

#49 ✨ Feat: #43 - button infinite scroll 기능 추가
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
Labels: Feat

#53 🎨 Design: #37 소환사 전적 검색 컴포넌트 디자인
  src/components/Main/InputID.tsx
  src/components/Main/Main.module.scss
  src/components/Record/Record.module.scss
  src/components/Record/Record.tsx
  src/components/Record/SummonerMatch/MatchInfo.module.scss
  src/components/Record/SummonerMatch/MatchInfo.tsx
  src/components/Record/SummonerMatch/MatchInfo/MatchInfo.module.scss
  src/components/Record/SummonerMatch/MatchInfo/MatchInfo.tsx
  src/components/Record/SummonerMatch/MatchInfo/MatchTeam/MatchTeam.module.scss
  src/components/Record/SummonerMatch/MatchInfo/MatchTeam/MatchTeam.tsx
  src/components/Record/SummonerMatch/SummonerMatch.module.scss
  src/components/Record/SummonerMatch/SummonerMatch.tsx
  src/components/Record/SummonerRank/SummonerRank.module.scss
  src/components/Record/types/type.ts
  src/styles/global.scss
Labels: Refactor, Design

#55 🎨 Design: #51 - Duo page 반응형웹 미디어쿼리 작업 완료
  src/components/Duo/Common/InputText/InputText.module.scss
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.module.scss
  src/components/Duo/DuoInfo/DuoInfo.module.scss
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/Duo/WriteDuo/WriteDuo.module.scss
  src/components/Duo/WriteDuo/WriteDuo.tsx
  src/components/Duo/utils/DuoType.ts
  src/firebase.ts
Labels: Fix, Design

#61 :recycle: Refactor: 중복코드 제거 및 css 코드 정리
  src/assets/LCK/Deft.webp
  src/assets/LCK/LCK2003.jpeg
  src/assets/LCK/logo_lck.svg
  src/components/LCK/LCK.module.scss
  src/components/LCK/LCK.tsx
  src/components/LCK/Lck_card_design.module.scss
  src/components/LCK/Zustand/useTeams.ts
  src/components/LCK/components/Constant/constant.ts
  src/components/LCK/components/Match/Match.module.scss
  src/components/LCK/components/Match/Schedule/Accordion/Accordion.module.scss
  src/components/LCK/components/Match/Schedule/Accordion/Accordion.tsx
  src/components/LCK/components/Match/Schedule/Item/Item.module.scss
  src/components/LCK/components/Match/Schedule/Item/Item.tsx
  src/components/LCK/components/Match/Schedule/Item/ItenResponsive.module.scss
  src/components/LCK/components/Match/Schedule/Month/Month.module.scss
  src/components/LCK/components/Match/Schedule/Month/Month.tsx
  src/components/LCK/components/Match/Schedule/No-schedule/No_Schedule.module.scss
  src/components/LCK/components/Match/Schedule/No-schedule/No_Schedule.tsx
  src/components/LCK/components/Match/Schedule/No_Schedule.module.scss
  src/components/LCK/components/Match/Schedule/Schedule.module.scss
  src/components/LCK/components/Match/Schedule/Schedule.tsx
  src/components/LCK/components/Match/Schedule/Sidebar/SideBar.module.scss
  src/components/LCK/components/Match/Schedule/Sidebar/SideBar.tsx
  src/components/LCK/components/Match/Schedule/Teams/Teams.module.scss
  src/components/LCK/components/Match/Schedule/Teams/Teams.tsx
  src/components/LCK/components/Match/Schedule/common/Button.tsx
  src/components/LCK/components/Team/Player/Player.module.scss
  src/components/LCK/components/Team/PlayerList/List.module.scss
  src/components/LCK/components/Team/PlayerList/PlayerList.module.scss
  src/components/LCK/components/Team/responsive.module.scss
  src/styles/global.scss
Labels: Refactor

#62 :ambulance: : Fix: 기능관련 코드 삭제해서 다시 복구 시켰습니다.
  src/components/LCK/Zustand/useMyTeam.ts
  src/components/LCK/components/Match/Schedule/Schedule.tsx
  src/components/LCK/components/Skeleton/SkeletonProfile.module.scss
  src/components/LCK/components/Skeleton/SkeletonResponsive.module.scss
  src/components/LCK/components/Team/Player/Player.module.scss
  src/styles/global.scss
Labels: Fix

#63 :art: Fix: ref 관련 에러 수정
  src/components/LCK/components/Match/Schedule/Schedule.tsx
  src/components/LCK/components/Team/Player/Player.tsx
  src/components/LCK/components/Team/TeamSlide/Logos.tsx
Labels: Fix

#64 👷 Chore: #60 - vercel.json 추가
  README.md
  vercel.json
Labels: Chore

#69 🎨 Fix: Duopage 필터기능 추가, 수정컴포넌츠 수정
  package-lock.json
  package.json
  src/components/Duo/Common/Filter/FilterRadio.tsx
  src/components/Duo/Common/InputText/InputText.tsx
  src/components/Duo/Constants/constant.ts
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.tsx
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/LCK/components/Team/TeamSlide/Logos.tsx
  src/firebase.ts
  src/hooks/useInput.tsx
  tsconfig.json
  vite.config.ts
Labels: Design
