Repository ZeroBGG/zero-gg, pull requests merged in 2023-02, with the labels that each got.

#78 🎨 Refactor: #77 - 공통 스타일 개선 및 시간 계산 로직 변경
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoInfo/DuoInfo.module.scss
  src/components/Record/Record.module.scss
  src/components/Record/Record.tsx
  src/components/Record/SummonerMatch/MatchInfo/MatchInfo.tsx
  src/components/Record/SummonerMatch/SummonerMatch.tsx
  src/route.module.scss
  src/route.tsx
  src/styles/global.scss
  vercel.json
Labels: Refactor, Design

#82 Delete .vercel directory
  .vercel/README.txt
  .vercel/cache/node/api/getDetailMatch.ts/tsconfig-with-tsconfig-json.json
  .vercel/cache/node/api/getMatch.ts/tsconfig-with-tsconfig-json.json
  .vercel/cache/node/api/getRotationChampion.ts/tsconfig-with-tsconfig-json.json
  .vercel/cache/node/api/getSummonerEntries.ts/tsconfig-with-tsconfig-json.json
  .vercel/cache/node/api/getSummonerInfo.ts/tsconfig-with-tsconfig-json.json
  .vercel/project.json
Labels: Refactor

#83 ⚡️ : pwa icon 수정
  index.html
  public/assets/icons/logo-32x32.png
  public/assets/icons/logo-48x48.png
  public/assets/icons/logo-64x64.png
  public/manifest.json
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.tsx
  src/components/Duo/DuoInfo/DuoInfo.tsx
Labels: Refactor

#86 🎨 Refactor: #85 - 코드 최적화 및 리팩토링
  index.html
  src/api/championApi.ts
  src/api/matchAPi.ts
  src/api/summonerApi.ts
  src/assets/LCK/No.png
  src/components/Common/NotFound/NotFound.module.scss
  src/components/Common/NotFound/NotFound.tsx
  src/components/Main/Circle.tsx
  src/components/Main/types/type.ts
  src/components/Record/Record.module.scss
  src/components/Record/Record.tsx
  src/components/Record/SummonerInfo/SummonerInfo.module.scss
  src/components/Record/SummonerMatch/MatchInfo/MatchInfo.module.scss
  src/components/Record/SummonerMatch/MatchInfo/MatchTeam/MatchTeam.module.scss
  src/components/Record/SummonerMatch/SummonerMatch.module.scss
  src/components/Record/SummonerMatch/SummonerMatch.tsx
  src/components/Record/SummonerRank/SummonerRank.module.scss
  src/components/Record/SummonerRank/SummonerRank.tsx
  src/hooks/useCircle.tsx
  src/pages/NotFound.tsx
  src/styles/global.scss
  sw.js
Labels: Refactor

#88 🎨 Refactor: Components, CSS
  src/components/Duo/Common/Filter/FilterRadio.tsx
  src/components/Duo/Common/InputText/InputText.tsx
  src/components/Duo/Duo.module.scss
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoCards/DuoCards.tsx
  src/components/Duo/ListDuo/ListDuo.module.scss
  src/components/Duo/ListDuo/ListDuo.tsx
  src/components/Duo/WriteDuo/WriteDuo.module.scss
  src/components/Duo/WriteDuo/WriteDuo.tsx
Labels: Refactor, Design

#93 ♻️ Refactor : DuoPage Refactoring
  index.html
  src/components/Duo/Common/Modal/Modal.module.scss
  src/components/Duo/Common/Modal/Modal.tsx
  src/components/Duo/Duo.tsx
  src/components/Duo/DuoInfo/DuoInfo.tsx
  src/components/Duo/ListDuo/DuoCards/DuoCards.module.scss
  src/components/Duo/ListDuo/DuoCards/DuoCards.tsx
  src/components/Duo/ListDuo/DuoInfo/DuoInfo.module.scss
  src/components/Duo/ListDuo/DuoInfo/DuoInfo.tsx
  src/components/Duo/ListDuo/ListDuo.tsx
  src/components/Duo/ListDuo/UpdateDuo/UpdateDuo.module.scss
  src/components/Duo/ListDuo/UpdateDuo/UpdateDuo.tsx
  src/components/Duo/WriteDuo/WriteDuo.module.scss
  src/components/Duo/WriteDuo/WriteDuo.tsx
  src/hooks/useInput.tsx
  src/route.tsx
Labels: Feat, Refactor

#96 :recycle: Refactor: 경로 에러 수정
  src/components/LCK/Zustand/useStore.ts
  src/components/LCK/components/Match/Schedule/Item/ItenResponsive.module.scss
  src/components/LCK/components/Match/Schedule/Noschedule/NoSchedule.tsx
  src/components/LCK/components/Match/Schedule/Schedule.tsx
  src/components/LCK/components/Match/Schedule/Teams/Teams.tsx
  src/components/LCK/components/Team/LanePostion/LanePositon.tsx
  src/components/LCK/components/Team/team_main/Team.tsx
  src/components/LCK/components/Team/team_main/responsive.module.scss
Labels: Refactor
